### ISSUE TITLE
dsg clutch pressure problem

### ISSUE THREAD

**Issue by DEN3535** [Switchleg1/SimosTools#7]
The pressure sensors in the dq500 have a small measurement error.  If the sensor shows for example - 0.01 bar instead of 0.0, then the logger displays the number 655 bar).  Please correct the problem and allow small negative values.  Changing the settings does not help solve the problem.

**Comment by DEN3535** [comment]
![Screenshot_20230722_150030_com app simostools_edit_4108200543354376](https://github.com/Switchleg1/SimosTools/assets/139713302/853346ce-fdd0-4e63-9a8e-26707f65513c)
![Screenshot_20230722_150055_com app simostools_edit_4108286579417904](https://github.com/Switchleg1/SimosTools/assets/139713302/ef72ad19-6d57-4271-9c70-c9aa362cd8fe)

**Comment by Switchleg1** [comment]
There is nothing to fix as this is the value the dq500 is reporting.  I am not butchering the app to accommodate dq500 quirks.

**Comment by DEN3535** [comment]
Just let the code show a small negative pressure.  The error of the sensors is valid for any gearboxes.  I just have a dq500 and noticed this bug.  The settings do not help (the code still returns the number 655

![Screenshot_20230722_122351_com app simostools_edit_4110740087742009](https://github.com/Switchleg1/SimosTools/assets/139713302/3d235089-b467-41f7-acaa-bfa4d5c7e33b)
![Screenshot_20230722_122431_com app simostools_edit_4110725539414407](https://github.com/Switchleg1/SimosTools/assets/139713302/648d3d8f-e3e8-4071-a832-4cc2af1c4a3b)

**Comment by DEN3535** [comment]
Incorrect pressure shows only at idle engine speed!  When the car is moving, the pressure dsg shows correctly)

**Comment by aarons3** [comment]
The app doesnt restrict what value is displayed.  The gauge min max is purely for the green bar graph display.

The app simply takes the output from the controller and converts it to a value in accordance with the equation provided etc.  Perhaps the equation is slightly different or it's a signed value on dq500, and the cause for the display error.  You'll need to set it on your own and import that as your DSG log list.

[PIDListDSG-USA.csv](https://github.com/Switchleg1/SimosTools/files/12136562/PIDListDSG-USA.csv)

**Comment by Switchleg1** [comment]
Its not a signing issue as the data type is unsigned, this is purely a bug with the dq500.  I have seen the same thing on certain dq381's as well.  If I were to modify the app to resolve this dq500 issue it would no longer be able to display 650nm and higher as this is the value being returned by your TCU.

**Comment by Switchleg1** [comment]
Never mind this is for the clutch pressure.  Easy fix, set this value to be signed in the csv.

**Comment by DEN3535** [comment]
Alternative program displays correctly🤔
![Screenshot_20230722_185654](https://github.com/Switchleg1/SimosTools/assets/139713302/d4f8745a-23f3-443a-bd29-29b037679b6e)

**Comment by DEN3535** [comment]
How to fix?  So?

**Comment by DEN3535** [comment]
![Screenshot_20230722_190928_com google android apps docs editors sheets_edit_4115274356241838](https://github.com/Switchleg1/SimosTools/assets/139713302/4aabc166-ad08-4a22-b347-6b6dd6402577)

**Comment by DEN3535** [comment]
The developer of the alternative program also corrected this error.  Here are his comments.  Perhaps it will help you figure out how to decrypt the data from the control unit.

![Screenshot_20230722_210006](https://github.com/Switchleg1/SimosTools/assets/139713302/0f665494-18de-4ecb-8cad-b5c35974e7ae)

**Comment by DEN3535** [comment]
![Screenshot_20230722_210006](https://github.com/Switchleg1/SimosTools/assets/139713302/0182f66d-5da7-4a1a-9994-493af4f156dd)

**Comment by DEN3535** [comment]
Odis is also great at seeing negative pressures

![IMG_20230722_224849_edit_4121680690234610](https://github.com/Switchleg1/SimosTools/assets/139713302/6f68752e-04ba-4f6b-8542-4c277e456ee3)

**Comment by aarons3** [comment]
Did you try changing it to a signed value yet?  Looks like no... Try this updated DSG log list 

[PIDListDSG-USA.csv](https://github.com/Switchleg1/SimosTools/files/12137160/PIDListDSG-USA.csv)

**Comment by DEN3535** [comment]
Friend.  Thank you.  The new file partially fixed the problem.  The 655 values ​​are no longer displayed.  Negative values ​​will be observed by other tools to track the slow death of dsg sensors)
![Screenshot_20230722_231108_com app simostools_edit_4123121309440120](https://github.com/Switchleg1/SimosTools/assets/139713302/284bdbf5-e98b-47cf-ae9b-3269c8082c6b)

**Comment by aarons3** [comment]
increase the decimal places if you want to see it, its just being rounded to 1 decimal.

**Comment by DEN3535** [comment]
Ok

**Comment by DEN3535** [comment]
😁👍
![Screenshot_20230723_085655_com app simostools_edit_4146076364250158](https://github.com/Switchleg1/SimosTools/assets/139713302/d169221c-9827-44e6-9c5b-880d7a1e4bb4)

**Comment by DEN3535** [comment]
By the way, the factory limits for the accuracy of pressure sensors are +/- 0.05
